language: java
sudo: false
jdk:
  - openjdk8
  - openjdk11

before_install:
  - "echo $JAVA_OPTS"
  - "export JAVA_OPTS=-Xmx512m"

script:
  - mvn install -B -V
  - mvn javadoc:jar
  - mvn javadoc:test-aggregate

